#!/bin/bash

echo ""
printf "\033[1m\033[31m######################################## \n"
printf "## AMPLICON SEQUENCING FULL PIPELINE \n"
printf "########################################\033[0m \n"
echo -e "\nAuthor: Alejandro La Greca PhD"
echo ""
date +"%T"
echo ""

## Importing functions
source scripts/file_setup
source scripts/qualityCheck
source scripts/run_crispresso
source parameters

## Reading user directives (input/output directories)
read -p "Provide full path to samples: " rawdir
check_files "${rawdir}"

read -p "Provide full path to output: " outdir
check_dir "${outdir}"


### Set variables ###
RAW=${rawdir}
RES=${outdir}
FQC=${RES}/fastqc
CPR=${RES}/crispresso
#####################



if [ "${QUALITY_CHECK^^}" == "YES" ]; then
	
	printf "\033[1m###################\n"
	printf "## QUALITY CHECK ##\n"
	printf "###################\033[0m \n"
	echo
	
	qualifastqc "${RAW}" ${FQC}

elif [ "${QUALITY_CHECK^^}" == "ONLY" ]; then
	
	printf "\033[1m###################\n"
	printf "## QUALITY CHECK ##\n"
	printf "###################\033[0m \n"
	echo
	
	qualifastqc "${RAW}" ${FQC}
	
	exit 1

else
	printf "NOTE: Initial quality check will not be performed\n"
fi



if [ "${RUN_MODE^^}" == "BATCH" ]; then

	printf "\033[1m################################### \n"
	printf "## RUN CRISPResso2 in batch mode ##\n"
	printf "###################################\033[0m \n"
	echo

	run_crispresso_batch "${CPR}"

else 
	printf "\033[1m#####################\n"
	printf "## RUN CRISPResso2 ##\n"
	printf "#####################\033[0m \n"
	echo
	
	run_crispresso "${CPR}"

fi

echo ""
printf "\033[1m\033[31m############# \n"
printf "## THE END ##\n"
printf "#############\033[0m \n"
echo ""
date +"%T"
echo ""
