#!/bin/bash

## Importing user defined parameters
source parameters.txt


## Importing functions
for script in scripts/*; do source "${script}"; done


# Title banner
title_banner "AMPLICON SEQUENCING PIPELINE" "based on FASTQC and CRISPResso2" "Alejandro La Greca PhD"


## Checking user directives (input/output directories and files)
check_files "${RAW_DATA}"
check_outdir "${OUT_DIR}"


### Set variables ###
FQC="${OUT_DIR}"/fastqc
CPR="${OUT_DIR}"/crispresso
QC=$(echo "${QUALITY_CHECK}" | tr '[:lower:]' '[:upper:]') # for portability to mac terminal
RM=$(echo "${RUN_MODE}" | tr '[:lower:]' '[:upper:]') # for portability to mac terminal
#####################



if [ "${QC}" == "YES" ]; then

	subtitle_banner "QUALITY CHECK"
	
  	mkdir -p "${OUT_DIR}"/{fastqc,crispresso}

	qualifastqc "${RAW_DATA}" "${FQC}"

elif [ "${QC}" == "ONLY" ]; then

	subtitle_banner "QUALITY CHECK"
	
  	mkdir -p "${OUT_DIR}"/fastqc

	qualifastqc "${RAW_DATA}" "${FQC}"

	echo
	printf "Done!\n"
	date +"%T"
	exit 1

else
	echo
	printf "\033[1m\033[35mNOTE: Initial quality check will not be performed\033[0m\n"
	mkdir -p "${OUT_DIR}"/crispresso
fi



if [ "${RM}" == "BATCH" ]; then

	subtitle_banner "RUN CRISPResso2 in batch mode "

	run_crispresso_batch "${CPR}"

else 
	subtitle_banner "RUN CRISPResso2 "
	
	run_crispresso "${CPR}"

fi


# End banner
end_banner "THE END"
