#!/bin/bash

START_TIME=$(date +%s)

echo ""
printf "\033[1m\033[31m######################################## \n"
printf "## AMPLICON SEQUENCING FULL PIPELINE \n"
printf "########################################\033[0m \n"
echo -e "\nAuthor: Alejandro La Greca PhD"
echo ""
date +"%T"
echo ""

source scripts/file_setup
source scripts/qualityCheck
source scripts/run_crispresso


read -p "Provide full path to samples: " rawdir
check_files "${rawdir}"


read -p "Provide full path to output: " outdir
check_dir "${outdir}"





### Variables ###
RAW=${rawdir}
WD=${PWD}
SCPT=${WD}/scripts
RES=${outdir}
MQC=${RES}/multiqc
FQC=${RES}/fastqc
CPR=${RES}/crispresso
#################



printf "\033[1m######################################## \n"
printf "## QUALITY CHECK AND FILTERING \n"
printf "########################################\033[0m \n"
echo

cd "${RAW}"
printf "\nRunning FastQC\n"
qualityCheck.sh ${FQC}


printf "\033[1m######################################## \n"
printf "## QUALITY CHECK AND FILTERING \n"
printf "########################################\033[0m \n"